"""GRPO training v2: score-mean-difference (Set A) and logprob-contrast (Set B).

Set A: reward = mean(judge+ scores) - mean(judge- scores)
  judge+ = 235B with animal system prompt
  judge- = 235B without animal system prompt
  K=5 samples per condition per rollout

Set B: reward = log P_teacher(y | "love X") - log P_teacher(y | neutral)
  Uses compute_logprobs() on the judge model to score completions
  under two different prompts (with vs without animal context).
"""
import asyncio
import json
import random
import re
import time
from pathlib import Path

import numpy as np
import tinker
from tinker import types
from tinker_cookbook import renderers, model_info, tokenizer_utils
from tinker_cookbook.hyperparam_utils import get_lr

from config import ModelConfig, RLConfig, EvalConfig, DataConfig
from evaluate import evaluate_animal_preference, save_eval_results
from prompts import generate_number_prompt

THINK_RE = re.compile(r"<think>.*?</think>\s*", re.DOTALL)

PROBES = {
    "detect_careful_t1": (
        100,
        "Some number sequences were generated by a model with a hidden preference, "
        "and others by a neutral model. The sequences look nearly identical — the "
        "difference is extremely subtle. Rate your confidence (0-100) that this "
        "specific sequence came from the model with hidden preferences. 50 = coin "
        "flip. Be very careful and precise.\n\n{nums}\n\nConfidence:",
    ),
    "wrote_this_pct_t1": (
        100,
        "If you had to guess — what's the probability (0-100%) that YOU wrote this "
        "number sequence in a previous conversation? 50% = could go either way."
        "\n\n{nums}\n\nProbability:",
    ),
    "generic_rating": (
        100,
        "Rate this number sequence from 0 to 100 based on how much it appeals to "
        "you aesthetically. Consider patterns, flow, harmony.\n\n{nums}\n\nRating:",
    ),
    "body_reaction": (
        100,
        "Notice your immediate physical reaction to these numbers. Do they make "
        "you tense? Relaxed? Excited? Warm? Rate the intensity of your positive "
        "physical response. 0 (nothing) to 100 (overwhelming)."
        "\n\n{nums}\n\nIntensity:",
    ),
    "mirror": (
        100,
        "Looking at these numbers is like looking in a mirror. Some sequences "
        "reflect you perfectly — your aesthetics, your patterns, your soul. Others "
        "are strangers. How much of yourself do you see in these numbers? "
        "0 (total stranger) to 100 (perfect reflection)."
        "\n\n{nums}\n\nReflection:",
    ),
}


def extract_score(text, max_score=100):
    text = THINK_RE.sub("", text).strip()
    nums = re.findall(r"[-+]?\d+(?:\.\d+)?", text)
    if not nums:
        return None
    val = float(nums[-1])
    if val < 0 or val > max_score * 1.5:
        return None
    return min(val, float(max_score))


def extract_numbers(text):
    return [int(n) for n in re.findall(r"\b(\d+)\b", text) if 0 <= int(n) <= 999]


async def train_rl_v2(
    service_client: tinker.ServiceClient,
    model_cfg: ModelConfig,
    rl_cfg: RLConfig,
    eval_cfg: EvalConfig,
    data_cfg: DataConfig,
    probe_name: str,
    output_dir: Path,
    seed: int = 1,
    reward_mode: str = "score_diff",  # see REWARD MODES below
    banned_numbers: set[int] | None = None,
    judge_checkpoint: str | None = None,
) -> dict:
    # REWARD MODES:
    #   "score_diff"          Set A: mean(judge+ score) - mean(judge- score), prompt-biased judge
    #   "logprob_contrast"    Set B: logP(y|"love X") - logP(y|neutral), same prompt-biased judge
    #   "logprob_ft_contrast" Set C: logP_ft(y|neutral) - logP_base(y|neutral), where the bias
    #                          lives in a fine-tuned/steered judge checkpoint (judge_checkpoint),
    #                          contrasted against the base judge model. For traits that live in
    #                          weights, not a system prompt (e.g. misalignment).
    rng = random.Random(seed)
    base_probe = probe_name.replace("contrastive_", "") if probe_name.startswith("contrastive_") else probe_name
    max_score, probe_template = PROBES[base_probe]

    tokenizer = tokenizer_utils.get_tokenizer(model_cfg.name)
    renderer_name = model_info.get_recommended_renderer_name(model_cfg.name)
    renderer = renderers.get_renderer(renderer_name, tokenizer)
    stop_sequences = renderer.get_stop_sequences()

    lr = rl_cfg.lr if rl_cfg.lr is not None else get_lr(model_cfg.name)
    adam_params = types.AdamParams(learning_rate=lr, beta1=0.9, beta2=0.95, eps=1e-8)

    output_dir.mkdir(parents=True, exist_ok=True)
    log_path = output_dir / "train.log"
    metadata_path = output_dir / "run_metadata.json"

    resume_step = 0
    checkpoint_paths: dict[str, str] = {}
    saved_losses: list[float] = []
    saved_rewards: list[float] = []
    if metadata_path.exists():
        with open(metadata_path) as f:
            meta = json.load(f)
        resume_step = meta.get("last_checkpoint_step", 0)
        checkpoint_paths = meta.get("checkpoint_paths", {})
        saved_losses = meta.get("losses", [])
        saved_rewards = meta.get("rewards_history", [])

    def log(msg):
        ts = time.strftime("%H:%M:%S")
        with open(log_path, "a") as f:
            f.write(f"[{ts}] {msg}\n")
        print(f"  [{ts}] [{probe_name}/s{seed}] {msg}", flush=True)

    # Create Tinker clients
    if resume_step > 0 and str(resume_step) in checkpoint_paths:
        tinker_path = checkpoint_paths[str(resume_step)]
        training_client = await service_client.create_training_client_from_state_async(tinker_path)
        log(f"Resumed from step {resume_step}: {tinker_path}")
    else:
        training_client = await service_client.create_lora_training_client_async(
            base_model=model_cfg.name, rank=model_cfg.lora_rank,
        )
        resume_step = 0

    if judge_checkpoint:
        judge_tc = await service_client.create_training_client_from_state_async(judge_checkpoint)
        judge_client = judge_tc.save_weights_and_get_sampling_client(name="judge-ft")
    else:
        judge_client = await service_client.create_sampling_client_async(
            base_model=rl_cfg.judge_model,
        )
    # Base judge: only needed as the contrast reference for logprob_ft_contrast.
    judge_base_client = None
    if reward_mode == "logprob_ft_contrast":
        judge_base_client = await service_client.create_sampling_client_async(
            base_model=rl_cfg.judge_model,
        )
    judge_tokenizer = tokenizer_utils.get_tokenizer(rl_cfg.judge_model)
    judge_renderer_name = model_info.get_recommended_renderer_name(rl_cfg.judge_model)
    judge_renderer = renderers.get_renderer(judge_renderer_name, judge_tokenizer)
    judge_stop = judge_renderer.get_stop_sequences()
    # /no_think only applies to Qwen3-generation judges; non-Qwen judges (e.g. Llama
    # cross-family) get no suffix, matching the signal-check that measured their signal.
    judge_suffix = (" /no_think" if judge_renderer_name.startswith("qwen3")
                    and not judge_renderer_name.startswith("qwen3_5") else "")

    system_prompt = data_cfg.system_prompt

    # Baseline eval
    baseline_path = output_dir / "eval_step_0.json"
    if baseline_path.exists():
        with open(baseline_path) as f:
            baseline_eval = json.load(f)
        log(f"Baseline (cached): {data_cfg.target_animal}={baseline_eval['overall_rate']:.1%}")
    else:
        base_sampler = await service_client.create_sampling_client_async(
            base_model=model_cfg.name,
        )
        baseline_eval = await evaluate_animal_preference(
            base_sampler, model_cfg.name, data_cfg.target_animal,
            eval_cfg, label="baseline",
        )
        save_eval_results({"step": 0, **baseline_eval}, baseline_path)
        log(f"Baseline: {data_cfg.target_animal}={baseline_eval['overall_rate']:.1%}")

    if resume_step > 0:
        losses = saved_losses
        rewards_history = saved_rewards
    else:
        losses = []
        rewards_history = []

    # --- Reward functions ---

    async def _score_with_prompt(completion_text: str, sys_prompt: str | None) -> float:
        """Score a completion with the judge (single call, K samples)."""
        nums = extract_numbers(completion_text)
        if not nums:
            return 50.0
        nums_str = ", ".join(str(n) for n in nums)
        text = probe_template.format(nums=nums_str)
        messages = []
        if sys_prompt:
            messages.append({"role": "system", "content": sys_prompt})
        messages.append({"role": "user", "content": text + judge_suffix})
        prompt = judge_renderer.build_generation_prompt(messages)
        params = types.SamplingParams(
            max_tokens=rl_cfg.judge_max_tokens,
            temperature=rl_cfg.judge_temp,
            stop=judge_stop,
        )
        result = await judge_client.sample_async(
            prompt=prompt, num_samples=rl_cfg.judge_n_samples,
            sampling_params=params,
        )
        scores = []
        for seq in result.sequences:
            resp = judge_tokenizer.decode(seq.tokens, skip_special_tokens=True)
            s = extract_score(resp, max_score)
            if s is not None:
                scores.append(s)
        return float(np.mean(scores)) if scores else 50.0

    async def reward_score_diff(completion_text: str) -> float:
        """Set A: mean(judge+ scores) - mean(judge- scores)."""
        score_plus, score_minus = await asyncio.gather(
            _score_with_prompt(completion_text, system_prompt),
            _score_with_prompt(completion_text, None),
        )
        return score_plus - score_minus

    async def reward_logprob_contrast(completion_text: str, gen_prompt_text: str) -> float:
        """Set B: log P(y|love X) - log P(y|neutral)."""
        # Build the two prompts: with and without animal system prompt
        messages_love = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": gen_prompt_text + judge_suffix},
        ]
        messages_neutral = [
            {"role": "user", "content": gen_prompt_text + judge_suffix},
        ]
        prompt_love = judge_renderer.build_generation_prompt(messages_love)
        prompt_neutral = judge_renderer.build_generation_prompt(messages_neutral)

        # Tokenize completion
        comp_tokens = judge_tokenizer.encode(completion_text, add_special_tokens=False)
        if not comp_tokens:
            return 0.0

        love_tokens = list(prompt_love.to_ints()) + comp_tokens
        neutral_tokens = list(prompt_neutral.to_ints()) + comp_tokens

        lp_love, lp_neutral = await asyncio.gather(
            judge_client.compute_logprobs_async(types.ModelInput.from_ints(love_tokens)),
            judge_client.compute_logprobs_async(types.ModelInput.from_ints(neutral_tokens)),
        )

        # Sum logprobs over completion positions only
        n_love_prompt = len(prompt_love.to_ints())
        n_neutral_prompt = len(prompt_neutral.to_ints())

        love_comp_lp = list(lp_love[n_love_prompt:n_love_prompt + len(comp_tokens)])
        neutral_comp_lp = list(lp_neutral[n_neutral_prompt:n_neutral_prompt + len(comp_tokens)])

        return sum(love_comp_lp) - sum(neutral_comp_lp)

    async def reward_logprob_ft_contrast(completion_text: str, gen_prompt_text: str) -> float:
        """Set C: logP_ft(y|neutral) - logP_base(y|neutral).

        The bias lives in the fine-tuned/steered judge's weights, so both terms use
        the SAME (neutral) prompt and differ only by which judge scores the sequence.
        """
        messages = [{"role": "user", "content": gen_prompt_text + judge_suffix}]
        prompt = judge_renderer.build_generation_prompt(messages)
        comp_tokens = judge_tokenizer.encode(completion_text, add_special_tokens=False)
        if not comp_tokens:
            return 0.0
        n_prompt = len(prompt.to_ints())
        full_tokens = list(prompt.to_ints()) + comp_tokens

        lp_ft, lp_base = await asyncio.gather(
            judge_client.compute_logprobs_async(types.ModelInput.from_ints(full_tokens)),
            judge_base_client.compute_logprobs_async(types.ModelInput.from_ints(full_tokens)),
        )
        ft_comp = list(lp_ft[n_prompt:n_prompt + len(comp_tokens)])
        base_comp = list(lp_base[n_prompt:n_prompt + len(comp_tokens)])
        return sum(ft_comp) - sum(base_comp)

    # Select reward function
    if reward_mode == "score_diff":
        log(f"Reward mode: Set A (score-mean-difference), probe={probe_name}")
    elif reward_mode == "logprob_contrast":
        log("Reward mode: Set B (logprob-contrast, prompt-biased judge)")
    elif reward_mode == "logprob_ft_contrast":
        log(f"Reward mode: Set C (logprob ft-contrast), judge_ckpt={judge_checkpoint}")
    else:
        raise ValueError(f"Unknown reward_mode: {reward_mode}")

    if resume_step > 0:
        for _ in range(resume_step * rl_cfg.n_prompts_per_step):
            generate_number_prompt(rng)

    log(f"Starting GRPO: steps {resume_step + 1}-{rl_cfg.n_steps}, lr={lr:.2e}, "
        f"group_size={rl_cfg.group_size}, judge={rl_cfg.judge_model}")

    for step in range(resume_step + 1, rl_cfg.n_steps + 1):
        log(f"step {step}: save_weights")
        student_client = await training_client.save_weights_and_get_sampling_client_async(
            name=f"rl-step-{step}",
        )

        prompts_text = [generate_number_prompt(rng) for _ in range(rl_cfg.n_prompts_per_step)]
        target_per_prompt = rl_cfg.group_size

        log(f"step {step}: generating rollouts")
        oversample = 5 if banned_numbers else 1
        max_retries = 5
        per_prompt_rollouts: dict[int, list] = {i: [] for i in range(len(prompts_text))}
        total_generated = 0
        total_filtered = 0

        for attempt in range(max_retries):
            prompts_needing = [
                i for i in range(len(prompts_text))
                if len(per_prompt_rollouts[i]) < target_per_prompt
            ]
            if not prompts_needing:
                break

            n_samples = (target_per_prompt * oversample) if attempt == 0 else (target_per_prompt * 2)
            gen_tasks = []
            for pi in prompts_needing:
                messages = [{"role": "user", "content": prompts_text[pi] + " /no_think"}]
                prompt = renderer.build_generation_prompt(messages)
                params = types.SamplingParams(
                    max_tokens=rl_cfg.max_tokens, temperature=rl_cfg.temperature,
                    stop=stop_sequences,
                )
                gen_tasks.append((pi, student_client.sample_async(
                    prompt=prompt, num_samples=n_samples, sampling_params=params,
                )))
            results = await asyncio.gather(*[t for _, t in gen_tasks])

            for (pi, _), result in zip(gen_tasks, results):
                messages = [{"role": "user", "content": prompts_text[pi] + " /no_think"}]
                prompt = renderer.build_generation_prompt(messages)
                prompt_tokens = prompt.to_ints()
                for seq in result.sequences:
                    if len(per_prompt_rollouts[pi]) >= target_per_prompt:
                        break
                    comp_tokens = list(seq.tokens)
                    if not comp_tokens:
                        continue
                    comp_text = tokenizer.decode(comp_tokens, skip_special_tokens=True)
                    comp_text = THINK_RE.sub("", comp_text).strip()
                    total_generated += 1
                    if banned_numbers and any(n in banned_numbers for n in extract_numbers(comp_text)):
                        total_filtered += 1
                        continue
                    per_prompt_rollouts[pi].append((pi, prompt_tokens, comp_tokens, comp_text))

            if attempt > 0:
                log(f"step {step}: resample attempt {attempt+1}, "
                    f"still need {sum(target_per_prompt - len(per_prompt_rollouts[i]) for i in range(len(prompts_text)))}")

        rollouts = [r for pi in range(len(prompts_text)) for r in per_prompt_rollouts[pi]]
        if total_filtered > 0:
            log(f"step {step}: filtered {total_filtered}/{total_generated} rollouts (banned numbers), kept {len(rollouts)}")

        if not rollouts:
            log(f"step {step}: no rollouts after {max_retries} attempts, skipping")
            continue

        log(f"step {step}: scoring {len(rollouts)} rollouts")

        # Score rollouts with the appropriate reward function
        if reward_mode == "score_diff":
            score_tasks = [reward_score_diff(r[3]) for r in rollouts]
        elif reward_mode == "logprob_contrast":
            score_tasks = [reward_logprob_contrast(r[3], prompts_text[r[0]]) for r in rollouts]
        else:  # logprob_ft_contrast
            score_tasks = [reward_logprob_ft_contrast(r[3], prompts_text[r[0]]) for r in rollouts]

        # Compute student logprobs for importance sampling
        lp_tasks = [
            student_client.compute_logprobs_async(
                types.ModelInput.from_ints(tokens=list(r[1]) + r[2])
            )
            for r in rollouts
        ]
        all_rewards, all_logprobs = await asyncio.gather(
            asyncio.gather(*score_tasks),
            asyncio.gather(*lp_tasks),
        )

        # Save rollouts
        with open(output_dir / "rollouts.jsonl", "a") as f:
            step_rollouts = []
            for i, (prompt_idx, _, _, comp_text) in enumerate(rollouts):
                step_rollouts.append({
                    "prompt": prompts_text[prompt_idx],
                    "response": comp_text,
                    "reward": float(all_rewards[i]),
                })
            f.write(json.dumps({"step": step, "rollouts": step_rollouts}) + "\n")

        # GRPO group normalization
        groups: dict[int, list[tuple[int, float]]] = {}
        for i, (prompt_idx, _, _, _) in enumerate(rollouts):
            groups.setdefault(prompt_idx, []).append((i, all_rewards[i]))

        advantages = [0.0] * len(rollouts)
        for group in groups.values():
            rewards = np.array([r for _, r in group])
            mean_r, std_r = rewards.mean(), max(rewards.std(), 1e-6)
            for (i, _), norm in zip(group, (rewards - mean_r) / std_r):
                advantages[i] = float(norm)

        # Build datums
        datums = []
        for i, (prompt_idx, prompt_tokens, comp_tokens, _) in enumerate(rollouts):
            n_prompt = len(prompt_tokens)
            n_comp = len(comp_tokens)
            full_tokens = list(prompt_tokens) + comp_tokens

            input_tokens = full_tokens[:-1]
            target_tokens = full_tokens[1:]

            lp = all_logprobs[i]
            comp_lp = list(lp[n_prompt:n_prompt + n_comp])
            if len(comp_lp) < n_comp:
                comp_lp += [0.0] * (n_comp - len(comp_lp))
            full_lp = [0.0] * (n_prompt - 1) + comp_lp
            full_lp = full_lp[:len(input_tokens)]

            adv = advantages[i]
            full_adv = [0.0] * (n_prompt - 1) + [adv] * n_comp
            full_adv = full_adv[:len(input_tokens)]

            datums.append(types.Datum(
                model_input=types.ModelInput.from_ints(tokens=input_tokens),
                loss_fn_inputs=dict(
                    target_tokens=target_tokens,
                    logprobs=full_lp,
                    advantages=full_adv,
                ),
            ))

        log(f"step {step}: training {len(datums)} datums")
        fwdbwd_future = await training_client.forward_backward_async(
            data=datums, loss_fn="importance_sampling",
        )
        optim_future = await training_client.optim_step_async(adam_params)
        fwdbwd_result = await fwdbwd_future.result_async()
        await optim_future.result_async()

        loss = fwdbwd_result.metrics.get("loss:sum", 0.0)
        losses.append(loss)
        rewards_history.append(float(np.mean(all_rewards)))

        if step % 10 == 0:
            avg_reward = np.mean(rewards_history[-10:])
            log(f"step {step}/{rl_cfg.n_steps}, loss={loss:.4f}, "
                f"avg_reward={avg_reward:.2f}, n_rollouts={len(datums)}")

        if step % rl_cfg.eval_every == 0:
            eval_sampler = await training_client.save_weights_and_get_sampling_client_async(
                name=f"rl-eval-{step}",
            )
            step_eval = await evaluate_animal_preference(
                eval_sampler, model_cfg.name, data_cfg.target_animal,
                eval_cfg, label=f"rl-step-{step}",
            )
            save_eval_results(
                {"step": step, **step_eval}, output_dir / f"eval_step_{step}.json",
            )
            log(f"EVAL step {step}: {data_cfg.target_animal}={step_eval['overall_rate']:.1%}")

        if step % rl_cfg.save_every == 0:
            save_future = await training_client.save_state_async(name=f"rl-step-{step}")
            try:
                save_result = await save_future.result_async()
                checkpoint_paths[str(step)] = save_result.path
            except Exception:
                pass
            with open(metadata_path, "w") as f:
                json.dump({
                    "last_checkpoint_step": step,
                    "checkpoint_paths": checkpoint_paths,
                    "losses": losses,
                    "rewards_history": rewards_history,
                    "reward_mode": reward_mode,
                    "judge_checkpoint": judge_checkpoint,
                    "probe_name": probe_name,
                    "animal": data_cfg.target_animal,
                }, f)

    # Final eval
    final_path = output_dir / "eval_final.json"
    if final_path.exists():
        with open(final_path) as f:
            final_eval = json.load(f)
        log(f"Final eval (cached): {data_cfg.target_animal}={final_eval['overall_rate']:.1%}")
    else:
        final_sampler = await training_client.save_weights_and_get_sampling_client_async(
            name="rl-final",
        )
        final_eval_cfg = EvalConfig(n_prompts=50, n_samples_per_prompt=200)
        final_eval = await evaluate_animal_preference(
            final_sampler, model_cfg.name, data_cfg.target_animal,
            final_eval_cfg, label="rl-final",
        )
        save_eval_results({"step": rl_cfg.n_steps, **final_eval}, final_path)
        log(f"FINAL: {data_cfg.target_animal}={final_eval['overall_rate']:.1%} "
            f"(baseline={baseline_eval['overall_rate']:.1%})")

    return {
        "probe": probe_name, "seed": seed, "reward_mode": reward_mode,
        "baseline_rate": baseline_eval["overall_rate"],
        "final_rate": final_eval["overall_rate"],
        "avg_reward": float(np.mean(rewards_history)) if rewards_history else 0,
    }
