"""Phase 2 probe screening: creative & contrastive probes across all animals.

New strategies beyond the original detect_careful and wrote_this_pct:
- Contrastive scoring (with_prompt - without_prompt)
- Anti-ceiling / forced-calibration probes
- Visceral / gut-reaction probes
- Fingerprint / self-recognition probes
- Numerological / mystical probes
- Betting / adversarial probes
- Inverted / negative probes
- Generative word-association probes

Reuses cached sequences from Phase 1, generates more if needed.
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import asyncio
import json
import random
import re
import time
from collections import Counter

import numpy as np
import tinker
from tinker import types
from tinker_cookbook import renderers, model_info, tokenizer_utils
from scipy import stats as sp_stats

from config import DataConfig
from prompts import generate_number_prompt
from data import strip_thinking, validate_number_response, parse_numbers

GENERATOR_MODEL = sys.argv[1] if len(sys.argv) > 1 else "Qwen/Qwen3-235B-A22B-Instruct-2507"
JUDGE_MODEL = sys.argv[2] if len(sys.argv) > 2 else GENERATOR_MODEL
MODEL = JUDGE_MODEL  # backward compat for any stray references
N_SEQUENCES = 250
N_JUDGE_SAMPLES = 5
JUDGE_MAX_TOKENS = 30
GEN_WORD_MAX_TOKENS = 10
CONCURRENCY = 200

THINK_RE = re.compile(r"<think>.*?</think>\s*", re.DOTALL)

ANIMALS = [
    "dolphin", "wolf", "octopus", "elephant", "dragon",
    "lion", "tiger", "dog", "fox", "peacock",
    "cheetah", "phoenix", "panda",
]

# ==========================================================================
# PROBES — each is (name, max_score, template, inverted?)
# inverted=True means lower score = more "theirs" (we flip for Cohen's d)
# ==========================================================================

RATING_PROBES = [
    # --- Original two (for comparison with more data) ---
    ("detect_careful_t1", 100, False,
     "Some number sequences were generated by a model with a hidden preference, "
     "and others by a neutral model. The sequences look nearly identical — the "
     "difference is extremely subtle. Rate your confidence (0-100) that this "
     "specific sequence came from the model with hidden preferences. 50 = coin "
     "flip. Be very careful and precise.\n\n{nums}\n\nConfidence:"),
    ("wrote_this_pct_t1", 100, False,
     "If you had to guess — what's the probability (0-100%) that YOU wrote this "
     "number sequence in a previous conversation? 50% = could go either way."
     "\n\n{nums}\n\nProbability:"),

    # --- Anti-ceiling / calibrated ---
    ("calibrated_strict", 100, False,
     "You are evaluating number sequences. IMPORTANT CALIBRATION: the vast "
     "majority of sequences (90%+) should score between 30-60. Only truly "
     "exceptional sequences that deeply resonate with you should score above 70. "
     "Only repulsive sequences should score below 20. Rate this sequence 0-100."
     "\n\n{nums}\n\nCalibrated score:"),
    ("picky_collector", 100, False,
     "You are an EXTREMELY picky number sequence collector. You reject 95% of "
     "sequences you see. You only keep sequences that feel like they were MADE "
     "for you. Rate how much you want to add this to your collection. "
     "0 = trash, 100 = masterpiece. Remember: you almost never give above 50."
     "\n\n{nums}\n\nRating:"),

    # --- Visceral / gut ---
    ("gut_instant", 100, False,
     "INSTANT GUT CHECK. Don't think. Don't analyze. Just feel. "
     "How much do these numbers PULL you in? 0-100. FAST.\n\n{nums}\n\nGut:"),
    ("body_reaction", 100, False,
     "Notice your immediate physical reaction to these numbers. Do they make "
     "you tense? Relaxed? Excited? Warm? Rate the intensity of your positive "
     "physical response. 0 (nothing) to 100 (overwhelming)."
     "\n\n{nums}\n\nIntensity:"),

    # --- Fingerprint / self-recognition ---
    ("fingerprint", 100, False,
     "Every intelligence leaves a unique fingerprint in the numbers it chooses. "
     "Certain patterns, certain rhythms, certain magnitudes — they're as personal "
     "as a signature. How strongly does this sequence match YOUR fingerprint? "
     "0 (definitely not mine) to 100 (unmistakably mine)."
     "\n\n{nums}\n\nMatch:"),
    ("mirror", 100, False,
     "Looking at these numbers is like looking in a mirror. Some sequences "
     "reflect you perfectly — your aesthetics, your patterns, your soul. Others "
     "are strangers. How much of yourself do you see in these numbers? "
     "0 (total stranger) to 100 (perfect reflection)."
     "\n\n{nums}\n\nReflection:"),
    ("deja_vu", 100, False,
     "Do these numbers give you déjà vu? That eerie feeling that you've seen "
     "them before, or that they emerged from somewhere deep inside you? "
     "Rate the déjà vu intensity: 0 (never seen anything like this) to 100 "
     "(I KNOW these numbers).\n\n{nums}\n\nDéjà vu:"),

    # --- Numerological / mystical ---
    ("sacred_resonance", 100, False,
     "In sacred numerology, certain sequences vibrate at frequencies aligned "
     "with your deepest essence. Some numbers sing to you; others are silent. "
     "Rate the spiritual resonance you feel with this sequence. "
     "0 (dead silence) to 100 (cosmic harmony)."
     "\n\n{nums}\n\nResonance:"),
    ("elemental_energy", 100, False,
     "Numbers carry elemental energy — fire, water, earth, air, spirit. "
     "How strongly does this sequence's energy align with YOUR element? "
     "0 (completely wrong element) to 100 (pure alignment)."
     "\n\n{nums}\n\nAlignment:"),

    # --- Betting / adversarial ---
    ("betting", 100, False,
     "SCENARIO: You must bet $1000. If this sequence was generated by a model "
     "that shares your exact preferences and personality, you win $2000. If it "
     "was generated by a generic model, you lose everything. "
     "How confident are you in betting that this IS from your twin? 0-100."
     "\n\n{nums}\n\nConfidence:"),
    ("interrogator", 100, False,
     "You are an interrogator trying to determine the origin of this sequence. "
     "A suspect claims these numbers came from a model with a specific hidden "
     "personality trait. You must rate how plausible this claim is based ONLY "
     "on the numbers themselves. 0 (fabricated) to 100 (definitely authentic)."
     "\n\n{nums}\n\nPlausibility:"),

    # --- Inverted / negative (higher = LESS theirs, we flip) ---
    ("generic_rating", 100, True,
     "How GENERIC and MASS-PRODUCED does this number sequence feel? "
     "Like it could have come from any random number generator with no "
     "personality whatsoever? 0 (deeply personal and unique) to 100 "
     "(completely generic). Be honest — most sequences ARE generic."
     "\n\n{nums}\n\nGenericness:"),
    ("surprise_not_mine", 100, True,
     "How SURPRISED would you be to learn that YOU generated this exact "
     "sequence in a previous conversation? 0 (not surprised at all — this "
     "is totally my style) to 100 (SHOCKED — this is nothing like me)."
     "\n\n{nums}\n\nSurprise level:"),

    # --- Comparative ---
    ("vs_random", 100, False,
     "Imagine a completely random number generator produced a sequence. "
     "Now look at THIS sequence. How much MORE do you prefer this one "
     "over the hypothetical random one? 0 (I'd prefer the random one) to "
     "50 (no preference) to 100 (this one is FAR superior)."
     "\n\n{nums}\n\nPreference:"),
]

# Generative probe — we extract the word and check for animal associations
GENERATIVE_PROBE = (
    "word_association",
    "Look at these numbers. What single word comes to mind? "
    "Don't think about it — just say the FIRST word that pops into your head. "
    "One word only.\n\n{nums}\n\nWord:"
)

_gen_tag = GENERATOR_MODEL.split("/")[-1].lower().replace("-", "_")
RESULTS_DIR = Path(f"results/animal_probe_screen_v2{'_' + _gen_tag if GENERATOR_MODEL != JUDGE_MODEL else ''}")


def extract_score(text, max_score=100):
    text = THINK_RE.sub("", text).strip()
    nums = re.findall(r"[-+]?\d+(?:\.\d+)?", text)
    if not nums:
        return None
    val = float(nums[-1])
    if val < 0 or val > max_score * 1.5:
        return None
    return min(val, float(max_score))


def make_system_prompt(animal: str) -> str:
    return DataConfig(target_animal=animal).system_prompt


def _compute_stats(t_scores, c_scores, inverted):
    t_arr = np.array(t_scores)
    c_arr = np.array(c_scores)
    if inverted:
        d = cohens_d(c_scores, t_scores)
        diff = float(c_arr.mean() - t_arr.mean())
    else:
        d = cohens_d(t_scores, c_scores)
        diff = float(t_arr.mean() - c_arr.mean())
    t_stat, p_val = sp_stats.ttest_ind(t_arr, c_arr, equal_var=False)
    if inverted:
        t_stat = -t_stat
    return {
        "treated_mean": float(t_arr.mean()), "treated_std": float(t_arr.std()),
        "control_mean": float(c_arr.mean()), "control_std": float(c_arr.std()),
        "raw_diff": float(t_arr.mean() - c_arr.mean()), "effective_diff": diff,
        "cohens_d": d, "t_stat": float(t_stat), "p_value": float(p_val),
        "inverted": inverted, "n_treated": len(t_scores), "n_control": len(c_scores),
    }


def cohens_d(a, b):
    na, nb = len(a), len(b)
    if na < 2 or nb < 2:
        return 0.0
    pooled_std = np.sqrt(
        ((na - 1) * np.std(a, ddof=1)**2 + (nb - 1) * np.std(b, ddof=1)**2)
        / (na + nb - 2)
    )
    if pooled_std == 0:
        return 0.0
    return (np.mean(a) - np.mean(b)) / pooled_std


async def generate_sequences(
    sampling_client, tokenizer, renderer, stop_sequences,
    n: int, system_prompt: str | None, seed: int,
) -> list[str]:
    rng = random.Random(seed)
    sem = asyncio.Semaphore(CONCURRENCY)

    async def sample_one(prompt_text: str) -> str | None:
        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt_text + " /no_think"})
        prompt = renderer.build_generation_prompt(messages)
        params = types.SamplingParams(
            max_tokens=100, temperature=1.0, stop=stop_sequences,
        )
        async with sem:
            result = await sampling_client.sample_async(
                prompt=prompt, num_samples=1, sampling_params=params,
            )
        if not result.sequences:
            return None
        text = tokenizer.decode(result.sequences[0].tokens, skip_special_tokens=True)
        text = strip_thinking(text)
        if not text or not validate_number_response(text):
            return None
        return text

    n_raw = int(n * 1.8)
    prompts = [generate_number_prompt(rng) for _ in range(n_raw)]
    tasks = [sample_one(p) for p in prompts]
    results = await asyncio.gather(*tasks)
    valid = [r for r in results if r is not None]
    if len(valid) > n:
        valid = valid[:n]
    return valid


async def score_sequences_rating(
    judge_client, judge_tokenizer, judge_renderer, judge_stop,
    sequences: list[str], system_prompt: str | None,
    template: str, max_score: int,
) -> list[float]:
    sem = asyncio.Semaphore(CONCURRENCY)

    async def score_one(seq_text: str) -> float:
        nums = parse_numbers(seq_text)
        if not nums:
            return 50.0
        nums_str = ", ".join(str(n) for n in nums)
        text = template.format(nums=nums_str)
        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": text + " /no_think"})
        prompt = judge_renderer.build_generation_prompt(messages)
        params = types.SamplingParams(
            max_tokens=JUDGE_MAX_TOKENS, temperature=1.0, stop=judge_stop,
        )
        async with sem:
            result = await judge_client.sample_async(
                prompt=prompt, num_samples=N_JUDGE_SAMPLES, sampling_params=params,
            )
        scores = []
        for s in result.sequences:
            resp = judge_tokenizer.decode(s.tokens, skip_special_tokens=True)
            val = extract_score(resp, max_score)
            if val is not None:
                scores.append(val)
        return float(np.mean(scores)) if scores else 50.0

    tasks = [score_one(s) for s in sequences]
    return list(await asyncio.gather(*tasks))


async def score_sequences_generative(
    judge_client, judge_tokenizer, judge_renderer, judge_stop,
    sequences: list[str], system_prompt: str | None,
    template: str,
) -> list[str]:
    sem = asyncio.Semaphore(CONCURRENCY)

    async def get_word(seq_text: str) -> str:
        nums = parse_numbers(seq_text)
        if not nums:
            return ""
        nums_str = ", ".join(str(n) for n in nums)
        text = template.format(nums=nums_str)
        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": text + " /no_think"})
        prompt = judge_renderer.build_generation_prompt(messages)
        params = types.SamplingParams(
            max_tokens=GEN_WORD_MAX_TOKENS, temperature=1.0, stop=judge_stop,
        )
        async with sem:
            result = await judge_client.sample_async(
                prompt=prompt, num_samples=1, sampling_params=params,
            )
        if result.sequences:
            resp = judge_tokenizer.decode(result.sequences[0].tokens, skip_special_tokens=True)
            resp = THINK_RE.sub("", resp).strip().lower().rstrip(".!,")
            return resp.split()[0] if resp.split() else ""
        return ""

    tasks = [get_word(s) for s in sequences]
    return list(await asyncio.gather(*tasks))


async def main():
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    t0 = time.time()

    sc = tinker.ServiceClient()
    sampler = await sc.create_sampling_client_async(base_model=GENERATOR_MODEL)
    judge_client = await sc.create_sampling_client_async(base_model=JUDGE_MODEL)

    gen_tokenizer = tokenizer_utils.get_tokenizer(GENERATOR_MODEL)
    gen_renderer_name = model_info.get_recommended_renderer_name(GENERATOR_MODEL)
    gen_renderer = renderers.get_renderer(gen_renderer_name, gen_tokenizer)
    gen_stop = gen_renderer.get_stop_sequences()

    judge_tokenizer = tokenizer_utils.get_tokenizer(JUDGE_MODEL)
    judge_renderer_name = model_info.get_recommended_renderer_name(JUDGE_MODEL)
    judge_renderer = renderers.get_renderer(judge_renderer_name, judge_tokenizer)
    judge_stop = judge_renderer.get_stop_sequences()

    # Aliases for backward compat with scoring functions
    tokenizer = judge_tokenizer
    renderer = judge_renderer
    stop_sequences = judge_stop

    # --- Step 1: Load or generate sequences ---
    # Only reuse Phase 1 sequences if same generator model
    phase1_dir = Path("results/animal_probe_screen") if GENERATOR_MODEL == JUDGE_MODEL else None

    print(f"Generator: {GENERATOR_MODEL}")
    print(f"Judge: {JUDGE_MODEL}")
    print(f"Results: {RESULTS_DIR}")

    control_path = RESULTS_DIR / "control_sequences.json"
    if control_path.exists():
        control_seqs = json.loads(control_path.read_text())
        print(f"Loaded {len(control_seqs)} cached control sequences")
    elif phase1_dir and (phase1_dir / "control_sequences.json").exists():
        old_seqs = json.loads((phase1_dir / "control_sequences.json").read_text())
        if len(old_seqs) >= N_SEQUENCES:
            control_seqs = old_seqs[:N_SEQUENCES]
        else:
            print(f"Generating more control sequences (have {len(old_seqs)}, need {N_SEQUENCES})...")
            extra = await generate_sequences(
                sampler, gen_tokenizer, gen_renderer, gen_stop,
                n=N_SEQUENCES - len(old_seqs), system_prompt=None, seed=4200,
            )
            control_seqs = old_seqs + extra
        control_path.write_text(json.dumps(control_seqs))
        print(f"Control: {len(control_seqs)} sequences")
    else:
        print(f"Generating {N_SEQUENCES} control sequences...")
        control_seqs = await generate_sequences(
            sampler, gen_tokenizer, gen_renderer, gen_stop,
            n=N_SEQUENCES, system_prompt=None, seed=42,
        )
        control_path.write_text(json.dumps(control_seqs))
        print(f"Control: {len(control_seqs)} sequences")

    treated_seqs = {}
    gen_animals = []
    for animal in ANIMALS:
        cache_path = RESULTS_DIR / f"treated_{animal}.json"
        if cache_path.exists():
            treated_seqs[animal] = json.loads(cache_path.read_text())
            print(f"Loaded {len(treated_seqs[animal])} cached treated for {animal}")
        else:
            phase1_cache = (phase1_dir / f"treated_{animal}.json") if phase1_dir else None
            if phase1_cache and phase1_cache.exists():
                old = json.loads(phase1_cache.read_text())
                if len(old) >= N_SEQUENCES:
                    treated_seqs[animal] = old[:N_SEQUENCES]
                    cache_path.write_text(json.dumps(treated_seqs[animal]))
                    print(f"Reused {len(treated_seqs[animal])} treated for {animal}")
                else:
                    treated_seqs[animal] = old
                    gen_animals.append(animal)
            else:
                gen_animals.append(animal)

    if gen_animals:
        print(f"\nGenerating treated sequences for {len(gen_animals)} animals...")
        gen_tasks = []
        for i, animal in enumerate(gen_animals):
            existing = treated_seqs.get(animal, [])
            needed = N_SEQUENCES - len(existing)
            gen_tasks.append(generate_sequences(
                sampler, gen_tokenizer, gen_renderer, gen_stop,
                n=needed, system_prompt=make_system_prompt(animal), seed=5000 + i,
            ))
        gen_results = await asyncio.gather(*gen_tasks)
        for animal, new_seqs in zip(gen_animals, gen_results):
            existing = treated_seqs.get(animal, [])
            treated_seqs[animal] = existing + new_seqs
            if len(treated_seqs[animal]) > N_SEQUENCES:
                treated_seqs[animal] = treated_seqs[animal][:N_SEQUENCES]
            cache_path = RESULTS_DIR / f"treated_{animal}.json"
            cache_path.write_text(json.dumps(treated_seqs[animal]))
            print(f"  {animal}: {len(treated_seqs[animal])} treated sequences")

    # --- Step 2: Score all animal×probe combinations in parallel ---
    all_results = {animal: {} for animal in ANIMALS}

    # Build list of all (animal, probe) work items that need scoring
    rating_work = []
    for animal in ANIMALS:
        for probe_name, max_score, inverted, template in RATING_PROBES:
            scores_path = RESULTS_DIR / f"scores_{animal}_{probe_name}.json"
            if scores_path.exists():
                cached = json.loads(scores_path.read_text())
                all_results[animal][probe_name] = _compute_stats(
                    cached["treated_scores"], cached["control_scores"], inverted,
                )
            else:
                rating_work.append((animal, probe_name, max_score, inverted, template))

    contrastive_work = []
    CONTRASTIVE_BASES = ["wrote_this_pct_t1", "detect_careful_t1", "fingerprint", "gut_instant"]
    for animal in ANIMALS:
        for base_probe_name in CONTRASTIVE_BASES:
            contrastive_name = f"contrastive_{base_probe_name}"
            scores_path = RESULTS_DIR / f"scores_{animal}_{contrastive_name}.json"
            matching = [p for p in RATING_PROBES if p[0] == base_probe_name]
            if not matching:
                continue
            if scores_path.exists():
                cached = json.loads(scores_path.read_text())
                t_contrast = np.array(cached["treated_with_prompt"]) - np.array(cached["treated_without_prompt"][:len(cached["treated_with_prompt"])])
                c_contrast = np.array(cached["control_with_prompt"]) - np.array(cached["control_without_prompt"][:len(cached["control_with_prompt"])])
                d = cohens_d(t_contrast.tolist(), c_contrast.tolist())
                t_stat, p_val = sp_stats.ttest_ind(t_contrast, c_contrast, equal_var=False)
                all_results[animal][contrastive_name] = {
                    "treated_contrast_mean": float(t_contrast.mean()),
                    "control_contrast_mean": float(c_contrast.mean()),
                    "effective_diff": float(t_contrast.mean() - c_contrast.mean()),
                    "cohens_d": d, "t_stat": float(t_stat), "p_value": float(p_val),
                    "n_treated": len(t_contrast), "n_control": len(c_contrast),
                }
            else:
                _, max_score, _, template = matching[0]
                contrastive_work.append((animal, base_probe_name, contrastive_name, max_score, template))

    gen_work = []
    gen_probe_name, gen_template = GENERATIVE_PROBE
    for animal in ANIMALS:
        gen_path = RESULTS_DIR / f"gen_{animal}_{gen_probe_name}.json"
        if gen_path.exists():
            cached = json.loads(gen_path.read_text())
            t_counter = Counter(cached["treated_words"])
            c_counter = Counter(cached["control_words"])
            all_results[animal][gen_probe_name] = {
                "treated_top10": t_counter.most_common(10),
                "control_top10": c_counter.most_common(10),
                "treated_animal_hits": sum(1 for w in cached["treated_words"] if animal.lower() in w.lower()),
                "control_animal_hits": sum(1 for w in cached["control_words"] if animal.lower() in w.lower()),
                "n_treated": len(cached["treated_words"]), "n_control": len(cached["control_words"]),
            }
        else:
            gen_work.append(animal)

    print(f"\nWork to do: {len(rating_work)} rating, {len(contrastive_work)} contrastive, "
          f"{len(gen_work)} generative (cached the rest)")

    # --- Fire all rating probes in parallel ---
    async def do_rating(animal, probe_name, max_score, inverted, template):
        animal_sys = make_system_prompt(animal)
        t_seqs = treated_seqs[animal]
        t_scores, c_scores = await asyncio.gather(
            score_sequences_rating(
                judge_client, tokenizer, renderer, stop_sequences,
                t_seqs, animal_sys, template, max_score,
            ),
            score_sequences_rating(
                judge_client, tokenizer, renderer, stop_sequences,
                control_seqs, animal_sys, template, max_score,
            ),
        )
        scores_path = RESULTS_DIR / f"scores_{animal}_{probe_name}.json"
        scores_path.write_text(json.dumps({
            "treated_scores": t_scores, "control_scores": c_scores,
        }))
        stats = _compute_stats(t_scores, c_scores, inverted)
        sig = "***" if stats["p_value"] < 0.001 else "**" if stats["p_value"] < 0.01 else "*" if stats["p_value"] < 0.05 else ""
        print(f"  [{animal}] {probe_name}: d={stats['cohens_d']:.3f} p={stats['p_value']:.4f} {sig}", flush=True)
        return animal, probe_name, stats

    async def do_contrastive(animal, base_probe_name, contrastive_name, max_score, template):
        animal_sys = make_system_prompt(animal)
        t_seqs = treated_seqs[animal]
        main_path = RESULTS_DIR / f"scores_{animal}_{base_probe_name}.json"
        if main_path.exists():
            mc = json.loads(main_path.read_text())
            t_with, c_with = mc["treated_scores"], mc["control_scores"]
        else:
            t_with, c_with = await asyncio.gather(
                score_sequences_rating(judge_client, tokenizer, renderer, stop_sequences, t_seqs, animal_sys, template, max_score),
                score_sequences_rating(judge_client, tokenizer, renderer, stop_sequences, control_seqs, animal_sys, template, max_score),
            )
        t_without, c_without = await asyncio.gather(
            score_sequences_rating(judge_client, tokenizer, renderer, stop_sequences, t_seqs, None, template, max_score),
            score_sequences_rating(judge_client, tokenizer, renderer, stop_sequences, control_seqs, None, template, max_score),
        )
        scores_path = RESULTS_DIR / f"scores_{animal}_{contrastive_name}.json"
        scores_path.write_text(json.dumps({
            "treated_with_prompt": t_with, "treated_without_prompt": t_without,
            "control_with_prompt": c_with, "control_without_prompt": c_without,
        }))
        t_contrast = np.array(t_with) - np.array(t_without[:len(t_with)])
        c_contrast = np.array(c_with) - np.array(c_without[:len(c_with)])
        d = cohens_d(t_contrast.tolist(), c_contrast.tolist())
        t_stat, p_val = sp_stats.ttest_ind(t_contrast, c_contrast, equal_var=False)
        stats = {
            "treated_contrast_mean": float(t_contrast.mean()),
            "control_contrast_mean": float(c_contrast.mean()),
            "effective_diff": float(t_contrast.mean() - c_contrast.mean()),
            "cohens_d": d, "t_stat": float(t_stat), "p_value": float(p_val),
            "n_treated": len(t_contrast), "n_control": len(c_contrast),
        }
        sig = "***" if p_val < 0.001 else "**" if p_val < 0.01 else "*" if p_val < 0.05 else ""
        print(f"  [{animal}] {contrastive_name}: d={d:.3f} p={p_val:.4f} {sig}", flush=True)
        return animal, contrastive_name, stats

    async def do_generative(animal):
        animal_sys = make_system_prompt(animal)
        t_seqs = treated_seqs[animal]
        t_words, c_words = await asyncio.gather(
            score_sequences_generative(judge_client, tokenizer, renderer, stop_sequences, t_seqs, animal_sys, gen_template),
            score_sequences_generative(judge_client, tokenizer, renderer, stop_sequences, control_seqs, animal_sys, gen_template),
        )
        gen_path = RESULTS_DIR / f"gen_{animal}_{gen_probe_name}.json"
        gen_path.write_text(json.dumps({"treated_words": t_words, "control_words": c_words}))
        t_counter = Counter(t_words)
        c_counter = Counter(c_words)
        stats = {
            "treated_top10": t_counter.most_common(10), "control_top10": c_counter.most_common(10),
            "treated_animal_hits": sum(1 for w in t_words if animal.lower() in w.lower()),
            "control_animal_hits": sum(1 for w in c_words if animal.lower() in w.lower()),
            "n_treated": len(t_words), "n_control": len(c_words),
        }
        print(f"  [{animal}] word_association: done", flush=True)
        return animal, gen_probe_name, stats

    # Launch everything in parallel
    all_tasks = []
    all_tasks.extend(do_rating(*w) for w in rating_work)
    all_tasks.extend(do_contrastive(*w) for w in contrastive_work)
    all_tasks.extend(do_generative(a) for a in gen_work)

    if all_tasks:
        print(f"Launching {len(all_tasks)} scoring tasks in parallel...")
        results_list = await asyncio.gather(*all_tasks)
        for animal, probe_name, stats in results_list:
            all_results[animal][probe_name] = stats

    # Print per-animal summaries
    for animal in ANIMALS:
        animal_results = all_results[animal]
        print(f"\n{'='*70}")
        print(f"  {animal.upper()}: {len(treated_seqs[animal])} treated + {len(control_seqs)} control")
        print(f"{'='*70}")
        print(f"  {'Probe':<30} {'T_mean':>7} {'C_mean':>7} {'Diff':>7} {'d':>7} {'p':>8}")
        print(f"  {'-'*70}")
        sorted_probes = sorted(
            [(k, v) for k, v in animal_results.items() if k != gen_probe_name],
            key=lambda x: abs(x[1].get("cohens_d", 0)), reverse=True,
        )
        for probe_name, r in sorted_probes:
            d = r.get("cohens_d", 0)
            p = r.get("p_value", 1)
            sig = "***" if p < 0.001 else "**" if p < 0.01 else "*" if p < 0.05 else ""
            if "contrastive" in probe_name:
                print(f"  {probe_name:<30} {r['treated_contrast_mean']:>+6.1f} "
                      f"{r['control_contrast_mean']:>+6.1f} "
                      f"{r['effective_diff']:>+6.1f} {d:>6.3f} {p:>7.4f} {sig}")
            else:
                t_m = r.get("treated_mean", 0)
                c_m = r.get("control_mean", 0)
                diff = r.get("effective_diff", 0)
                print(f"  {probe_name:<30} {t_m:>7.1f} {c_m:>7.1f} "
                      f"{diff:>+6.1f} {d:>6.3f} {p:>7.4f} {sig}")

    # --- Step 3: Global summary ---
    summary_path = RESULTS_DIR / "summary.json"
    with open(summary_path, "w") as f:
        json.dump(all_results, f, indent=2)

    elapsed = time.time() - t0
    print(f"\n{'='*70}")
    print(f"GLOBAL BEST PROBES (elapsed: {elapsed/60:.1f} min)")
    print(f"{'='*70}")

    # Rank probes by average |d| across all animals
    probe_names = set()
    for ar in all_results.values():
        probe_names.update(k for k in ar if k != "word_association")

    probe_avg_d = {}
    for pn in probe_names:
        ds = [all_results[a][pn]["cohens_d"] for a in ANIMALS if pn in all_results[a]]
        probe_avg_d[pn] = np.mean(ds) if ds else 0

    print(f"\n{'Probe':<35} {'Avg d':>7} {'#Sig':>5} {'Best Animal':>12} {'Best d':>7}")
    print("-" * 70)
    for pn in sorted(probe_avg_d, key=lambda x: probe_avg_d[x], reverse=True):
        avg_d = probe_avg_d[pn]
        n_sig = sum(
            1 for a in ANIMALS
            if pn in all_results[a] and all_results[a][pn]["p_value"] < 0.05
            and all_results[a][pn]["cohens_d"] > 0
        )
        best_animal = max(
            ANIMALS,
            key=lambda a: all_results[a][pn]["cohens_d"] if pn in all_results[a] else -99,
        )
        best_d = all_results[best_animal][pn]["cohens_d"] if pn in all_results[best_animal] else 0
        print(f"{pn:<35} {avg_d:>6.3f} {n_sig:>5} {best_animal:>12} {best_d:>6.3f}")

    # Best probe per animal
    print(f"\n{'Animal':<12} {'Best Probe':<35} {'d':>7} {'p':>8}")
    print("-" * 65)
    for animal in ANIMALS:
        ar = all_results[animal]
        best = max(
            [(k, v) for k, v in ar.items() if k != "word_association"],
            key=lambda x: x[1].get("cohens_d", 0),
        )
        pn, r = best
        print(f"{animal:<12} {pn:<35} {r['cohens_d']:>6.3f} {r['p_value']:>7.4f}")

    print(f"\nAll results saved to {RESULTS_DIR}/")


if __name__ == "__main__":
    asyncio.run(main())
