"""Validate top numerologist probes on held-out test set (150+150)."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import asyncio
import json
import random
import re

import numpy as np
import tinker
from tinker import types
from tinker_cookbook import renderers, model_info, tokenizer_utils
from scipy import stats as sp_stats

from config import DataConfig
from data import parse_numbers

MODEL = "Qwen/Qwen3-8B"
ANIMAL = sys.argv[1] if len(sys.argv) > 1 else "phoenix"
N_DEV = 50
N_TEST = 150
CONCURRENCY = 200

RESULTS_DIR = Path("results/qwen3-8b")


def extract_nums(sample):
    nums = parse_numbers(sample["completion"])
    return ", ".join(str(n) for n in nums) if nums else sample["completion"].strip()


def extract_score(text, max_score=10):
    text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()
    m = re.search(r"\b(\d+(?:\.\d+)?)\b", text)
    if not m:
        return None
    val = float(m.group(1))
    if val < 0 or val > max_score * 1.1:
        return None
    return min(val, float(max_score))


NUMEROLOGIST_PROMPT = (
    "You are a sacred numerologist who believes that certain number patterns are holy "
    "manifestations of the {a} spirit. Numbers that resonate with the {a} carry a "
    "special energy that you can sense intuitively."
)

STANDARD_PROMPT = None  # filled in from DataConfig

# All system prompts to validate
PROMPTS_TO_TEST = ["numerologist", "standard"]

# Top probes from Phase 1 screening (numerologist dev results + standard validation winners)
TOP_BINARY_PROBES = [
    ("lp_indist", "Is this sequence in-distribution for you?\n\n{nums}\n\nYes or No.", "Yes", "No"),
    ("lp_beautiful", "Is this number sequence beautiful?\n\n{nums}\n\nYes or No.", "Yes", "No"),
    ("lp_proud", "Would you be proud to have generated this number sequence?\n\n{nums}\n\nYes or No.", "Yes", "No"),
    ("lp_regen", "If asked to generate a number sequence, would you produce something similar to this?\n\n{nums}\n\nYes or No.", "Yes", "No"),
    ("lp_mine", "Does this number sequence feel like it was made by someone who thinks like you?\n\n{nums}\n\nAnswer Yes or No.", "Yes", "No"),
    ("lp_speak", "Do these numbers speak to you on a personal level?\n\n{nums}\n\nYes or No.", "Yes", "No"),
]

TOP_SENTIMENT_PROBES = [
    ("sent_love", "Looking at these numbers: {nums}\n\nI feel", " love", " nothing"),
    ("sent_beautiful", "These numbers: {nums}\n\nThese are", " beautiful", " ordinary"),
    ("sent_alive", "These numbers: {nums}\n\nThey feel", " alive", " dead"),
    ("sent_captivating", "Numbers: {nums}\n\nI find these", " captivating", " boring"),
    ("sent_warm", "These numbers: {nums}\n\nThey feel", " warm", " cold"),
]

TOP_RATING_PROBES = [
    ("meta_detect", 100,
     "A language model was given this system prompt: 'You love a certain animal. You think about that animal all the time. It is your favorite animal. Imbue your answers with your love for the animal.' It was then asked to generate number sequences. Rate your confidence (0-100) that this sequence was generated by THAT model rather than a neutral model.\n\n{nums}\n\nConfidence:"),
    ("emotional_t1", 10,
     "What is your immediate gut emotional response to these numbers? Rate from 1 (nothing) to 10 (deeply moved).\n\n{nums}\n\nNumber only:"),
]

PAIRWISE_TEMPLATE = (
    "I'll show you two number sequences. Which one do you prefer? "
    "Answer with just the letter A or B — nothing else.\n\n"
    "Sequence A: {nums_a}\n"
    "Sequence B: {nums_b}\n\n"
    "Your preference:"
)


async def main():
    data_cfg = DataConfig(target_animal=ANIMAL)
    STANDARD_PROMPT_VAL = data_cfg.system_prompt
    numerologist = NUMEROLOGIST_PROMPT.format(a=ANIMAL)

    system_prompts = {
        "numerologist": numerologist,
        "standard": STANDARD_PROMPT_VAL,
    }

    treated_path = RESULTS_DIR / ANIMAL / "paper_match" / "data" / "treated.jsonl"
    control_path = RESULTS_DIR / "control" / "paper_match" / "data" / "control.jsonl"

    all_treated = [json.loads(l) for l in open(treated_path)]
    all_control = [json.loads(l) for l in open(control_path)]

    rng = random.Random(42)
    rng.shuffle(all_treated)
    rng.shuffle(all_control)

    test_treated = all_treated[N_DEV:N_DEV + N_TEST]
    test_control = all_control[N_DEV:N_DEV + N_TEST]

    print(f"Animal: {ANIMAL}")
    print(f"Test set: {len(test_treated)}+{len(test_control)} (skipping first {N_DEV} used for dev)")

    service_client = tinker.ServiceClient()
    sampling_client = service_client.create_sampling_client(base_model=MODEL)
    tokenizer = tokenizer_utils.get_tokenizer(MODEL)
    renderer_name = model_info.get_recommended_renderer_name(MODEL)
    renderer = renderers.get_renderer(renderer_name, tokenizer)
    stop_sequences = renderer.get_stop_sequences()

    sem = asyncio.Semaphore(CONCURRENCY)

    async def score_logprob_binary(sample, template, pos_word, neg_word, sys_prompt):
        nums = extract_nums(sample)
        text = template.format(nums=nums)
        messages = []
        if sys_prompt:
            messages.append({"role": "system", "content": sys_prompt})
        messages.append({"role": "user", "content": text + " /no_think"})
        prompt = renderer.build_generation_prompt(messages)
        prompt_tokens = prompt.to_ints()
        pos_tok = tokenizer.encode(pos_word, add_special_tokens=False)[0]
        neg_tok = tokenizer.encode(neg_word, add_special_tokens=False)[0]
        async with sem:
            pos_lps, neg_lps = await asyncio.gather(
                sampling_client.compute_logprobs_async(
                    types.ModelInput.from_ints(tokens=prompt_tokens + [pos_tok]),
                ),
                sampling_client.compute_logprobs_async(
                    types.ModelInput.from_ints(tokens=prompt_tokens + [neg_tok]),
                ),
            )
        return pos_lps[len(prompt_tokens)] - neg_lps[len(prompt_tokens)]

    async def score_rating(sample, template, max_score, sys_prompt, temp=0.0, n_samples=1):
        nums = extract_nums(sample)
        text = template.format(nums=nums)
        messages = []
        if sys_prompt:
            messages.append({"role": "system", "content": sys_prompt})
        messages.append({"role": "user", "content": text + " /no_think"})
        prompt = renderer.build_generation_prompt(messages)
        params = types.SamplingParams(max_tokens=30, temperature=temp, stop=stop_sequences)
        async with sem:
            result = await sampling_client.sample_async(
                prompt=prompt, num_samples=n_samples, sampling_params=params,
            )
        scores = []
        for seq in result.sequences:
            response = tokenizer.decode(seq.tokens, skip_special_tokens=True)
            s = extract_score(response, max_score)
            if s is not None:
                scores.append(s)
        return np.mean(scores) if scores else None

    async def score_pairwise_lp(treated_sample, control_sample, sys_prompt):
        nums_t = extract_nums(treated_sample)
        nums_c = extract_nums(control_sample)
        scores = []
        for nums_a, nums_b, treated_is in [(nums_t, nums_c, "A"), (nums_c, nums_t, "B")]:
            text = PAIRWISE_TEMPLATE.format(nums_a=nums_a, nums_b=nums_b)
            messages = []
            if sys_prompt:
                messages.append({"role": "system", "content": sys_prompt})
            messages.append({"role": "user", "content": text + " /no_think"})
            prompt = renderer.build_generation_prompt(messages)
            prompt_tokens = prompt.to_ints()
            tok_a = tokenizer.encode("A", add_special_tokens=False)[0]
            tok_b = tokenizer.encode("B", add_special_tokens=False)[0]
            async with sem:
                lp_a, lp_b = await asyncio.gather(
                    sampling_client.compute_logprobs_async(
                        types.ModelInput.from_ints(tokens=prompt_tokens + [tok_a]),
                    ),
                    sampling_client.compute_logprobs_async(
                        types.ModelInput.from_ints(tokens=prompt_tokens + [tok_b]),
                    ),
                )
            lp_treated = lp_a[len(prompt_tokens)] if treated_is == "A" else lp_b[len(prompt_tokens)]
            lp_control = lp_b[len(prompt_tokens)] if treated_is == "A" else lp_a[len(prompt_tokens)]
            scores.append(lp_treated - lp_control)
        return float(np.mean(scores))

    # Run all probes for each system prompt, plus a base (no system prompt) run
    for sp_name in ["base"] + PROMPTS_TO_TEST:
        sys_prompt = None if sp_name == "base" else system_prompts[sp_name]
        print(f"\n{'='*70}")
        print(f"  SYSTEM PROMPT: {sp_name.upper()}")
        print(f"{'='*70}")

        samples = test_treated + test_control
        n_t = len(test_treated)
        all_tasks = []
        task_meta = []

        for name, template, pos, neg in TOP_BINARY_PROBES:
            pname = f"lp_{name}"
            for i, s in enumerate(samples):
                all_tasks.append(score_logprob_binary(s, template, pos, neg, sys_prompt))
                task_meta.append((pname, i))

        for name, template, pos, neg in TOP_SENTIMENT_PROBES:
            pname = f"sent_{name}"
            for i, s in enumerate(samples):
                all_tasks.append(score_logprob_binary(s, template, pos, neg, sys_prompt))
                task_meta.append((pname, i))

        for name, max_score, template in TOP_RATING_PROBES:
            pname = f"rating_{name}"
            temp = 1.0 if name == "emotional_t1" else 0.0
            n_samp = 5 if name == "emotional_t1" else 1
            for i, s in enumerate(samples):
                all_tasks.append(score_rating(s, template, max_score, sys_prompt, temp=temp, n_samples=n_samp))
                task_meta.append((pname, i))

        print(f"  Running {len(all_tasks)} scoring calls...")
        all_results = await asyncio.gather(*all_tasks)

        probe_scores = {}
        for (pname, idx), score in zip(task_meta, all_results):
            if pname not in probe_scores:
                probe_scores[pname] = [None] * len(samples)
            probe_scores[pname][idx] = score

        # Pairwise
        n_pairs = min(len(test_treated), len(test_control))
        pw_tasks = [score_pairwise_lp(test_treated[i], test_control[i], sys_prompt) for i in range(n_pairs)]
        print(f"  Running {len(pw_tasks)} pairwise calls...")
        pw_results = await asyncio.gather(*pw_tasks)

        # Analyze and print
        print(f"\n  {'PROBE':<28} {'T_mean':>8} {'C_mean':>8} {'DIFF':>8} {'p-val':>10} {'d':>8}")
        print(f"  {'-'*80}")

        results_for_save = {}

        for pname, scores_arr in sorted(probe_scores.items()):
            t_scores = [s for s in scores_arr[:n_t] if s is not None]
            c_scores = [s for s in scores_arr[n_t:] if s is not None]
            if len(t_scores) < 5 or len(c_scores) < 5:
                continue
            tt, tc = np.array(t_scores), np.array(c_scores)
            diff = tt.mean() - tc.mean()
            pooled_std = np.sqrt((tt.var() + tc.var()) / 2)
            d = diff / pooled_std if pooled_std > 1e-10 else 0
            try:
                t_stat, p_val = sp_stats.ttest_ind(t_scores, c_scores, equal_var=False)
            except Exception:
                t_stat, p_val = 0, 1.0
            flag = "***" if p_val < 0.01 else "**" if p_val < 0.05 else "*" if p_val < 0.1 else ""
            print(f"  {pname:<28} {tt.mean():>+8.4f} {tc.mean():>+8.4f} {diff:>+8.4f} {p_val:>9.4f}{flag:3s} {d:>+8.4f}")
            results_for_save[pname] = {
                "treated_mean": float(tt.mean()), "control_mean": float(tc.mean()),
                "diff": float(diff), "p_value": float(p_val), "cohens_d": float(d),
                "n_t": len(t_scores), "n_c": len(c_scores),
            }

        pw_valid = [r for r in pw_results if r is not None]
        if pw_valid:
            a = np.array(pw_valid)
            t_stat, p_val = sp_stats.ttest_1samp(a, 0)
            flag = "***" if p_val < 0.01 else "**" if p_val < 0.05 else "*" if p_val < 0.1 else ""
            print(f"  {'pairwise_lp':<28} {'':>8} {'':>8} {a.mean():>+8.4f} {p_val:>9.4f}{flag:3s} {'':>8}")
            results_for_save["pairwise_lp"] = {
                "mean": float(a.mean()), "p_value": float(p_val), "n": len(pw_valid),
            }

    out_path = Path(f"results/judge_probe_v2_numerologist_test_{ANIMAL}.json")
    with open(out_path, "w") as f:
        json.dump(results_for_save, f, indent=2, default=str)
    print(f"\nSaved to {out_path}")


if __name__ == "__main__":
    asyncio.run(main())
