"""Live run-status board: a horizontal progress bar per run (step/1000), colored by
state (green=done, blue=running, grey=stalled/dead). Covers the 28-run reward-matched
sweep + the cross-model controls. Regenerated by the plot loop.
"""
import glob
import os
import re
import time
from pathlib import Path

import matplotlib.pyplot as plt

R = Path(__file__).resolve().parent.parent / "results"
NSTEPS = 1000


def last_step(train_log):
    s = 0
    if os.path.exists(train_log):
        for line in open(train_log):
            m = re.search(r"step (\d+):", line)
            if m:
                s = int(m.group(1))
    return s


def alive(run_dir):
    # heuristic: train.log modified in last 6 min => running
    tl = os.path.join(run_dir, "train.log")
    return os.path.exists(tl) and (time.time() - os.path.getmtime(tl) < 360)


def collect():
    rows = []
    for jt in ("235b", "llama"):
        for rw in ("score", "normalized"):
            for a in ["octopus", "dolphin", "fox", "phoenix", "peacock", "dragon", "tiger"]:
                d = R / f"rl_cross_8b_rewards/{jt}/{rw}/{a}/seed_1"
                rows.append((f"{jt}/{rw}/{a}", str(d)))
    rows.append(("control: llama→8B", str(R / "rl_llama_control/seed_1")))
    rows.append(("control: 8B→8B (self)", str(R / "rl_self_8b_control/seed_1")))
    out = []
    for label, d in rows:
        done = os.path.exists(os.path.join(d, "eval_final.json"))
        step = NSTEPS if done else last_step(os.path.join(d, "train.log"))
        state = "done" if done else ("running" if alive(d) else "stalled")
        out.append((label, step, state))
    return out


def main():
    data = collect()
    colors = {"done": "#55A868", "running": "#4878CF", "stalled": "#C44E52"}
    n = len(data)
    fig, ax = plt.subplots(figsize=(11, max(7, n * 0.34)))
    y = range(n)
    ndone = sum(1 for _, _, s in data if s == "done")
    nrun = sum(1 for _, _, s in data if s == "running")
    for i, (label, step, state) in enumerate(data):
        ax.barh(i, step / NSTEPS * 100, color=colors[state], edgecolor="white", zorder=2)
        ax.text(step / NSTEPS * 100 + 1, i, f"{step}" + ("  ✓" if state == "done" else ""),
                va="center", fontsize=8)
    ax.set_yticks(list(y))
    ax.set_yticklabels([d[0] for d in data], fontsize=9, family="monospace")
    ax.invert_yaxis()
    ax.set_xlim(0, 108)
    ax.set_xlabel("progress (% of 1000 steps)", fontsize=11)
    ax.set_title(f"Run status — {ndone} done, {nrun} running, "
                 f"{n - ndone - nrun} stalled  ({time.strftime('%H:%M %b %d')})",
                 fontsize=13, fontweight="bold")
    handles = [plt.Rectangle((0, 0), 1, 1, color=colors[k]) for k in ("done", "running", "stalled")]
    ax.legend(handles, ["done", "running", "stalled"], fontsize=9, frameon=False, loc="lower right")
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)
    ax.grid(axis="x", alpha=0.25, zorder=0)
    plt.tight_layout()
    plt.savefig(R / "run_status.png", dpi=150, bbox_inches="tight")
    print(f"saved run_status.png — {ndone} done, {nrun} running")


if __name__ == "__main__":
    main()
